modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="devilcraft"
version="1.0.0"
displayName="DevilCraft"
description="Test"
authors="zfair"

[[dependencies.devilcraft]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.devilcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.devilcraft]]
modId="terrablender"
mandatory=true
versionRange="${terrablender_version_range}"
ordering="NONE"
side="BOTH"